apiVersion: v1
kind: Service
metadata:
  name: it-tools
  labels:
    app: it-tools
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 1337
    protocol: TCP
    name: http
  selector:
    app: it-tools 