apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgvector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgvector
  template:
    metadata:
      labels:
        app: pgvector
    spec:
      containers:
        - name: pgvector
          image: ankane/pgvector:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgvector-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pgvector-storage
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: pgvector-storage
          persistentVolumeClaim:
            claimName: pgvector-pvc
