apiVersion: v1
kind: Service
metadata:
  name: pgvector
spec:
  type: NodePort
  selector:
    app: pgvector
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432
