apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hoarder

configMapGenerator:
  - name: hoarder-configuration
    literals:
      - NEXTAUTH_URL=http://localhost:3000
      - HOARDER_VERSION=release
      - DISABLE_SIGNUPS=true

resources:
- namespace.yaml
- hoarder-secret.yaml
- web/deployment.yaml
- web/service.yaml
- chrome/deployment.yaml
- chrome/service.yaml
- meilisearch/deployment.yaml
- meilisearch/service.yaml
- meilisearch/pvc.yaml
- data-pvc.yaml

replacements:
- source:
    fieldPath: data.HOARDER_VERSION
    kind: ConfigMap
    name: hoarder-configuration
    version: v1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.image
    options:
      delimiter: ':'
      index: 1
    select:
      group: apps
      kind: Deployment
      name: web
      version: v1