apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:latest
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 2368
        env:
        - name: database__client
          value: sqlite3
        - name: url
          value: "http://localhost:2368"
        volumeMounts:
        - name: ghost-content
          mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost-content
        emptyDir: {}
        