apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: nextjs-docker-tunnel
  namespace: nextjs-docker
subjects:
  - name: nextjs-docker # Name of our service 
tunnelRef:
  kind: ClusterTunnel
  name: k3s-cluster-tunnel
env:
  - name: POSTGRES_URL
    valueFrom:
      secretKeyRef:
        name: nextjs-docker-secrets
        key: POSTGRES_URL