apiVersion: v1
data:
    POSTGRES_URL: ENC[AES256_GCM,data:TwB/jT905EV6mtBqXLBuoACrSU+RvA58rspiqaKfe3M/vmVzdP3EPgPdiD1CtPjA6n060WOYozJKTOgIld2byy6tnC8p2sHnRgbp4r3s1YDI60Owuwu10aDW/stPAyKrqFfg621SNBfijQi6+bc0LDeaVWTXmYnMXlXCUOlLcbpGwJhNrV9bI4HC6EM=,iv:t4ISJoeeepk+N/FfSvH7wXeQtgyBd2tlMdgODJ8KlOc=,tag:1ir6e7hcF0OA1RkJJG5CPA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: nextjs-docker-secrets
    namespace: nextjs-docker
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ud0yttnv9520zh4ekfhzs7p2ggwe7uwjx8p6dzzhuujx4epkap7sm4djqp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZyswRHg1MVhkNUpNZWZi
            dngwRU5ZQmN0WmwzVTRzV0RoQ09WRStOQzFNCmdBbzgxdmx6VDlKT3V0MnJocUpZ
            d3VXcCtKYTMreWplT2xSaU1RdWFpa2sKLS0tIEMxVE12V0Q0MUNKeDg5OUJSN0VG
            YnpwdTRjNWR3WXNWcHdHOTFRSlFDZE0K5aB1WqYOG+DDw44t5/17HC0eq9/XDclv
            ECJLaZk5JnlG6EMQtkA+xTdcVGzirVAtu9/bd84nMUBrvlLwD5vuYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-09T18:35:43Z"
    mac: ENC[AES256_GCM,data:/pkklxC72MWEi2lTZJJLGDf44ApKAkf7KqUd7JObGew839Y3vxISijS3sd4wR6kX16YIkOiTrOS9JGWSEUKQiiqpK5T8WV0vZRaUx0HNLs6ktv2tZRrTzqnyWavjWDU8uzkzy50Am8axD8PXvl3y9jF5b7CEYMc6iBXDnVzwQnY=,iv:3JaCOq5DkQYWDGNulFcoCREc63TZczac6tWyaFlZ9tw=,tag:s+Y1NmguWrH0lYAkZf/Uow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
