apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: homeassistant-tunnel
  namespace: homeassistant
subjects:
  - name: homeassistant # Name of our service 
    ingress:
      - hostname: homeassistant.lanham.ai
        service: http://homeassistant-service.homeassistant:8123
tunnelRef:
  kind: ClusterTunnel
  name: k3s-cluster-tunnel